sudo: false
language: node_js
node_js:
  - 16
branches:
  only:
    - main
notifications:
  email: false
before_script:
  - npm prune
  - npm run test
script:
  - npm run build
after_success:
  - npm run semantic-release
